import 'package:flutter/painting.dart';
import 'package:flutter/material.dart';
class ColorValues {
  /*deliva_pa App colors*/
    static const int primaryColor = 0XFFFF782D;
  static const int yellow_light = 0XFFFEC92D;
  static const int white = 0XFFFFFFFF;
  static const int accentColor = 0XFFFF782D;
 // static const int accentColor = 0XFFFEC32D;
  static const int blueTheme = 0XFF187897;
  static const int yellowTheme = 0XFFFEC32D;
  static const int sea_blue = 0XFF2394BC;
  static const int backgroundColorOp = 0XFFFFF9F5;
  static const int black = 0XFF000000;
  static const int black_light = 0XFF6C6C6C;
  static const int black_light_new = 0XFF1B1E25;
  static const int sea_green_blue_light = 0XFF4C5669;
  static const int notificationGreyTextColor = 0XFF929292;
  static const int text_view_hint = 0XFF8A8D8D;
  static const int text_view_theme = 0XFF8A8D8D;
  static const int text_green = 0XFF50BE0D;
  static const int text_red = 0XFFFF0606;
  static const int text_complete_deatils = 0XFFFF5F44;
  static const int grey_light = 0XFF555555;
  static const int grey_hint_color = 0XFF949494;
  static const int grey_light_tab = 0XFFA9ADB5;
  static const int grey_light_header = 0XFF959292;
  static const int grey_light_text = 0XFF7A7B7D;
  static const int grey_light_divider = 0XFFCBCBCB;
  static const int error_red = 0XFFF44336;
  static const int password_text = 0XFFF5F5F5F;
  static const int unselected_tab_text_color = 0XFFFC2C2C2;
  static const int acceptedBidColorBlue = 0XFF007AEB;
  static const int inTransitColorGreen = 0XFF2FB80C;
  static const int greyTextColorLight = 0XFF999999;
  static const int greyViewColor = 0XFFE6E9EB;
    static const int orangeLight = 0XFFFF782D;
    static const int warning_red = 0XFFEB2222;
    static const int greyCardBorder = 0XFFEEEEEE;

    static const int lightPinkColor = 0XFFFF8DBD;
    static const int lightYellowColor = 0XFFFFC670;
    static const int lightGreenColor = 0XFFB1FFA5;
    static const int lightPurpleColor = 0XFFE7B3FF;
    static const int lightBlueColor = 0XFF7CFFF7;
    static const int lightOrangeColor = 0XFFFFA47C;

    static const int notificationMonthTextColor = 0XFFB5B5B5;
    static const int greyDividerColor = 0XFFBBBBBB;
    static const int unreadTextColor = 0XFFA7A7A7;
    static const int transactionTextColor = 0XFF2A2A2A;
    static const int transactionLightTextColor = 0XFFA9A9A9;
    static const int helpTextColor = 0XFF8A8D8D;
    static const int ligthhelpTextColor = 0XFFB8B8B8;
    static const int radioTextColor = 0XFFc4c4c4;

  static const int NAVIGATION_DRAWER_BG_COLOUR = 0XFFF7F7F9;
  static const int BOTTOAMBAR_ADD_BG_COLOUR= 0XFF3C79DB;
  static const int HOME_TEXT_COLOUR= 0XFF606062;
  static const int HOME_BG_COLOUR= 0XFFf7f7f8;
  static const int BUTTON_TEXT_GRAY = 0xFF97a3b2;
  static const int BUTTON_TEXT_BLUE = 0xFF5185e8;
  static const int BUTTON_LOGIN_BG = 0xFFf8f9fb;
//  static const int BLUE_COLOR = 0xFF3B79E0;
  static const int BLUE_COLOR = 0xFF4684EB;
  static const int BLUE_COLOR_BOTTOMBAR = 0xFF4684EB;
  static const int HEADING_COLOR = 0xFFC1E3FC;
  static const int HEADING_COLOR_EDUCATION = 0xFF151515;
  static const int SCREEN_BG_COLOR= 0xFFFAFAFA;
  static const int GREY_TEXT_COLOR= 0xFF9A9C9C;
  static const int LIGHT_GREY_TEXT_COLOR= 0xFFE9E9EC;
  static const int RADIO_BLACK= 0xFF151515;
  static const int GRAY_HEADER_PRESSO_VIEW = 0xffCACACA;
  static const int LIGHT_GRAY_BG= 0xffF8F9F8;
  static const int OPPORTUNITY_GROUP_SELECTION_GRP = 0xffF0F0F0;
  static const int GRAY_BG = 0xffF8F8F8;

  static const int DEVIDER_COLOR = 0xffE9E9EC;
  static const int DARK_GREY = 0xffDEDEDE;
  static const int BORDER_COLOR = 0xffDEDEDE;
  static const int BG_CIRCLE_COLOR = 0xffA0A0A0;
  static const int WHITE = 0xffffffff;
  static const int RED = 0xffFD0000;
  static const int SELECTION_GRAY = 0xffF0F0F0;
  static const int SEARCH_CATEGORY_BOX_BG = 0xffC1E3FC;
  static const int SEARCH_CATEGORY_BOX_BG_SELCTED = 0xff4684EB;
}
